
server.port=8190

demo.users[0].id=1
demo.users[0].user-name=zhangsan
demo.users[0].password=123456
demo.users[0].email=zhangsan@example.com
demo.users[0].telephone=13800000001
demo.users[0].create-by=system
demo.users[0].create-time=2026-01-01 00:00:00

demo.users[1].id=2
demo.users[1].user-name=lisi
demo.users[1].password=123456
demo.users[1].email=lisi@example.com
demo.users[1].telephone=13800000002
demo.users[1].create-by=system
demo.users[1].create-time=2026-01-02 00:00:00
